### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by nosvalds** [Azure/aci-deploy#28]
I'm trying to use the master branch of azure/aci-deploy since v1 contains the error with set-env in @actions/core (which was fixed with https://github.com/Azure/aci-deploy/pull/27), but now I'm getting an error where the '@actions/core' module can't be found.

I tried forking the repo and creating a v2 to see if that would resolve it, but no luck.

```
2020-11-17T15:17:51.9589709Z ##[group]Run azure/aci-deploy@master
2020-11-17T15:17:51.9590224Z with:
2020-11-17T15:17:51.9590722Z   resource-group: ***
2020-11-17T15:17:51.9591312Z   dns-name-label: prd-container-iati-devops
2020-11-17T15:17:51.9592322Z   image: ***/prd-cont-img-iati-devops:36f5112357cf884cc63a105829a2ef08ec56bb2c
2020-11-17T15:17:51.9593256Z   registry-login-server: ***
2020-11-17T15:17:51.9594072Z   registry-username: ***
2020-11-17T15:17:51.9594694Z   registry-password: ***
2020-11-17T15:17:51.9595205Z   name: prd-container-iati-devops
2020-11-17T15:17:51.9595700Z   location: uksouth
2020-11-17T15:17:51.9596040Z   cpu: 1
2020-11-17T15:17:51.9596402Z   ip-address: Public
2020-11-17T15:17:51.9596753Z   memory: 1.5
2020-11-17T15:17:51.9597085Z   os-type: Linux
2020-11-17T15:17:51.9597461Z   ports: 80
2020-11-17T15:17:51.9597789Z   protocol: TCP
2020-11-17T15:17:51.9598198Z   restart-policy: Always
2020-11-17T15:17:51.9598562Z env:
2020-11-17T15:17:51.9598898Z   STAGE: prd
2020-11-17T15:17:51.9599537Z   IMAGE_NAME: cont-img-iati-devops
2020-11-17T15:17:51.9600110Z   CONTAINER_NAME: container-iati-devops
2020-11-17T15:17:51.9600675Z   TAG: 36f5112357cf884cc63a105829a2ef08ec56bb2c
2020-11-17T15:17:51.9601173Z   AZURE_HTTP_USER_AGENT: 
2020-11-17T15:17:51.9601581Z   AZUREPS_HOST_ENVIRONMENT: 
2020-11-17T15:17:51.9602095Z   DOCKER_CONFIG: /home/runner/work/_temp/docker_login_1605626249059
2020-11-17T15:17:51.9602546Z ##[endgroup]
2020-11-17T15:17:51.9931218Z internal/modules/cjs/loader.js:800
2020-11-17T15:17:51.9931730Z     throw err;
2020-11-17T15:17:51.9932094Z     ^
2020-11-17T15:17:51.9932299Z 
2020-11-17T15:17:51.9933146Z Error: Cannot find module '@actions/core'
2020-11-17T15:17:51.9933619Z Require stack:
2020-11-17T15:17:51.9934657Z - /home/runner/work/_actions/azure/aci-deploy/master/lib/main.js
2020-11-17T15:17:51.9936232Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
2020-11-17T15:17:51.9937274Z     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
2020-11-17T15:17:51.9937983Z     at Module.require (internal/modules/cjs/loader.js:852:19)
2020-11-17T15:17:51.9938601Z     at require (internal/modules/cjs/helpers.js:74:18)
2020-11-17T15:17:51.9939952Z     at Object.<anonymous> (/home/runner/work/_actions/azure/aci-deploy/master/lib/main.js:19:27)
2020-11-17T15:17:51.9940618Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-11-17T15:17:51.9941345Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-11-17T15:17:51.9941991Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2020-11-17T15:17:51.9942627Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2020-11-17T15:17:51.9943404Z     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
2020-11-17T15:17:51.9944191Z   code: 'MODULE_NOT_FOUND',
2020-11-17T15:17:51.9944913Z   requireStack: [ '/home/runner/work/_actions/azure/aci-deploy/master/lib/main.js' ]
2020-11-17T15:17:51.9945465Z ***
2020-11-17T15:17:52.0025493Z Post job cleanup.
```

**Comment by remyjette** [comment]
`node_modules` has to be checked in.

https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

**Comment by mitsha-microsoft** [comment]
You can't use the master branch directly, you will need a new tagged released branch. To run it in your fork, you can follow the following steps:

1. Fork the repo.
2. Fork a separate branch (to be used for running the action)
3. Do an `npm install` and `npm run build` and check in the `node_modules` folder to the branch as well.
4. Now you can refer to this action's branch and it should work

This is just a temporary solution until the new version gets deployed

**Comment by anraghun** [comment]
@nosvalds `node_modules` are checked into the release branches. Closing this as the new release is being tracked in #26.
